- name: "Sending Command"
  hosts: r4vmx
  tasks:
    - name: Send Command with xml output
# https://docs.ansible.com/ansible/2.9/modules/junos_command_module.html#junos-command-module
      junos_command:  
        commands:
          - show interfaces
        display: xml
    
      register: cli_result

    - name: "Printing Result"
      debug:
        msg: "{{ cli_result['stdout'] }}"

    - name: Create xml output file
      copy:
        content: "{{ cli_result['stdout'] | first }}"
        dest: Interfaces_output.xml