- name: "Getting Facts"
  hosts: r4vmx_netconf
  tasks:
    - name: Gather facts
# https://docs.ansible.com/ansible/2.9/modules/junos_facts_module.html#junos-facts-module
      junos_facts:  
        gather_subset: 
          - config    
      register: cli_result

    - name: "Printing Facts"
      debug:
        msg: "{{ cli_result['ansible_facts']['ansible_net_config'] }}"

    - name: Create config output file
      copy:
        content: "{{ ansible_net_config }}"
        dest: "{{ ansible_net_hostname }}_config_output.txt"
