- name: "Getting Configs"
  hosts: r4vmx_netconf
  tasks:
    - name: Get Configs
# https://docs.ansible.com/ansible/2.9/modules/junos_rpc_module.html#junos-rpc-module
      junos_rpc:
        rpc: get-configuration 

      register: cli_result

    - name: "Printing Result"
      debug:
        msg: "{{ cli_result }}"

    - name: Create config output file
      copy:
        content: "{{ cli_result['xml']  }}"
        dest: "RPC_config_output.xml"