---
- name: "RestConf Enable"
  hosts: r3iosxe
  connection: network_cli
  tasks:
    - name: Sending Configuerations
    # https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_config_module.html#ansible-collections-cisco-ios-ios-config-module
      cisco.ios.ios_config:
        lines:
        - ip http secure-server
        - restconf
      register: cli_result

    - name: "Printing result"
      debug:
        msg: "{{ cli_result }}"