---
- name: "Get Configs"
  hosts: r4iosxe_api
  connection: local
  tasks:

    - name: Connect via RestConf 
    # https://docs.ansible.com/ansible/latest/collections/ansible/netcommon/restconf_get_module.html
      ansible.netcommon.restconf_get:
        content: all
        output: json
        # path: /ietf-routing:routing-state/
        # path: /openconfig-local-routing:local-routes/state/
        path: /Cisco-IOS-XE-ospf-oper:ospf-oper-data/
      register: cli_result

    - name: Printing Result
      debug: 
        msg: "{{ cli_result }}"