---
- name: "Get VRF with Filter"
  hosts: r3iosxe_api
  connection: local
  tasks:

    - name: Connect via RestConf 
    # https://docs.ansible.com/ansible/latest/collections/ansible/netcommon/restconf_get_module.html
      ansible.netcommon.restconf_get:
        content: all
        output: json
        path: /ietf-routing:routing/routing-instance=OE_NET
      register: cli_result

    - name: Printing Result
      debug: 
        msg: "{{ cli_result['response'] }}"