---
- name: "Get Interfaces"
  hosts: r4iosxe_api
  connection: local
  tasks:

    - name: Connect via RestConf 
    # https://docs.ansible.com/ansible/latest/collections/ansible/netcommon/restconf_get_module.html
      ansible.netcommon.restconf_get:
        content: all
        output: json
        # path: /ietf-interfaces:interfaces-state/interface
        path: /ietf-interfaces:interfaces-state/interface?fields=name;speed;admin-status;
      register: cli_result

    - name: Printing Result
      debug: 
        msg: "{{ cli_result['response'] }}"