---
- name: "Geting Facts"
  hosts: fw1_fgt7
  connection: local
  vars:
    vdom: "root"
  tasks:
    - name: Get multiple selectors info concurrently
      fortinet.fortios.fortios_configuration_fact:
        selector: 'system_global'

      register: cli_result

    - name: "Printing Facts"
      debug:
        msg: "{{ cli_result }}"