---
- name: "Set Hostname"
  hosts: fw1_fgt7
  connection: httpapi
  vars:
    vdom: "root"
  tasks:
    - name: Setting Hostname
      # https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/gen/fortios_system_global.html
      fortinet.fortios.fortios_system_global:
        access_token: "{{ fortios_access_token }}"
        vdom:  "{{ vdom }}"
        system_global:
          hostname: "OE-FW-01"

      register: cli_result

    - name: "Printing Facts"
      debug:
        msg: "{{ cli_result }}"