---
- name: "Create Interface"
  hosts: fw1_fgt7
  collections:
  - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
  tasks:
    - name: Creating Interface
    # https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/gen/fortios_system_interface.html
      fortios_system_interface:
        vdom:  "{{ vdom }}"
        state: "present"
        
        system_interface:
          vdom: "{{ vdom }}"
          name: "LoopBack4"
          type: "loopback"
          ip: "192.168.4.4 255.255.255.255"
          description: "Created by Ansible"
          allowaccess: "ping"

      register: cli_result

    - name: "Printing Facts"
      debug:
        msg: "{{ cli_result }}"

