---
- name: "Get Interface Parse"
  hosts: fw1_fgt7
  connection: httpapi
  vars:
    vdom: "root"
  tasks:
    - name: Getting Interfaces Configuration
    # https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/fortios_configuration_fact.html
      fortinet.fortios.fortios_configuration_fact:
        access_token: "{{ fortios_access_token }}"
        selector: 'system_interface'

      register: cli_result

    - name: "Printing Facts"
      debug:
        msg: "{{ cli_result| json_query('meta.results[*].name') }}"
        # msg: "{{ cli_result| json_query('meta.results[*].[name,ip,description]') }}"
