---
- name: "Create and Assign Zone"
  hosts: fw1_fgt7
  collections:
  - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"

  tasks:
  - name: Creating and Assigning Zone
  # https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/gen/fortios_system_global.html
    fortios_system_zone:
      vdom:  "{{ vdom }}"
      state: "present"
      system_zone:
        name: "DMZ"
        interface: 
          - interface_name: "P4.100"
        intrazone: "allow"

    register: cli_result


  - name: "Printing Facts"
    debug:
      msg: "{{ cli_result }}"
