---
- name: "Get DHCP Settings"
  hosts: fw1_fgt7
  connection: httpapi
  vars:
    vdom: "root"
  tasks:
    - name: Getting DHCP Settings
      # https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/fortios_configuration_fact.html
      fortinet.fortios.fortios_configuration_fact:

        selector: 'system.dhcp_server'

      register: cli_result

    - name: "Printing Facts"
      debug:
        msg: "{{ cli_result }}"