---
- name: "Get Objects"
  hosts: fw1_fgt7
  collections:
  - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
    Q_1: "meta.results[?type == 'ipmask' ]"
    Q_2: "meta.results[?type == 'ipmask' ].[name,ip]"

  tasks:
  - name: Getting IP addresses objects Parsed
# https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/fortios_configuration_fact.html
    fortios_configuration_fact:
        
        selector: 'firewall_address'

    register: cli_result


  - name: "Printing Facts"
    debug:
      msg: "{{ cli_result | json_query(Q_1)}}"
      # msg: "{{ cli_result | json_query(Q_2)}}"
