---
- name: "Create IP Address"
  hosts: fw1_fgt7
  collections:
  - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"

  tasks:
  - name: Creating IP Address
# https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/gen/fortios_firewall_address.html
    fortios_firewall_address:
        vdom: "{{ vdom }}"
        state: "present"
        firewall_address:

          name: "IP_OE_172.16.24.70/32"
          type: "ipmask"
          subnet: "172.16.24.70 255.255.255.255"
          comment: "Created By Ansible"

    register: cli_result


  - name: "Printing Facts"
    debug:
      msg: "{{ cli_result | json_query('meta.results')}}"
