---
- name: "Get Policies"
  hosts: fw1_fgt7
  collections:
  - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"

  tasks:
  - name: Getting Policies
# https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/fortios_configuration_fact.html
    fortios_configuration_fact:
        
        selector: 'firewall_policy'

    register: cli_result


  - name: "Printing Facts"
    debug:
      msg: "{{ cli_result | json_query('meta.results')}}"
