---
- hosts: local
  vars:
    IP_Addr: 
      R1: 192.168.1.1
      R2: 192.168.1.2
      SW1: 192.168.1.3

  tasks:
    - name: Print 
      debug:
        msg: "The IP is: {{ IP_Addr }}"
        # msg: "The IP is: {{ IP_Addr['R1'] }}"