---
- hosts: local
  vars:
    IP_Addr: 
      R1: 192.168.1.1
      R2: 192.168.1.2
      SW1: 192.168.1.3

  tasks:
    - name: "Printing with loop"
      debug:
        msg: "{{ item.key }} - {{ item.value }}"
      with_dict: "{{ IP_Addr }}"
