---
- hosts: local
  vars:
    IP_Addr: 
      - orhanergun.net
      - SW1
      - 192.168.1.3
  tasks:
    - name: Print IP only
      debug:
        msg: "This is an IP {{ item }}"
      loop: "{{ IP_Addr }}"
      when: item | ipv4 